version: '3'
services:
  innoter-frontend:
    container_name: innoter-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - innoter_static_volume:/usr/src/app/innoter_static
      - innoter_media_volume:/usr/src/app/innoter_media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4200:3000
    networks:
      - innoter_innoter-network

networks:
  innoter_innoter-network:
    external: true

volumes:
  innoter_static_volume:
    external: true
  innoter_media_volume:
    external: true