version: '3'
services:
  innoter-frontend:
    container_name: innoter-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - build_volume:/app/build
  innoter-nginx:
    image: nginx:1.21.0-alpine
    container_name: innoter-nginx
    ports:
      - ${NGINX_APP_PORT}:3000
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - innoter_static_volume:/usr/src/app/innoter_static
      - innoter_media_volume:/usr/src/app/innoter_media
      - build_volume:/usr/src/app/build
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - innoter_innoter-network


networks:
  innoter_innoter-network:
    external: true

volumes:
  build_volume:
  innoter_static_volume:
    external: true
  innoter_media_volume:
    external: true