version: '3'
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - innoter_static_volume:/usr/src/app/innoter_static
      - innoter_media_volume:/usr/src/app/innoter_media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4200:${APP_PORT}
    networks:
      - user-management-service_app-network
      - innoter_innoter-network
networks:
  user-management-service_app-network:
    external: true
  innoter_innoter-network:
    external: true

volumes:
  database_volume:
  celery_logs:
  build_volume:
  innoter_static_volume:
    external: true
  innoter_media_volume:
    external: true